kernel:
  image: linuxkit/kernel:4.14.59
  cmdline: "console=tty0 ipAddress=192.168.58.10 ipBroadcast=192.167.57.255 ipMask=24"
init:
  - wombat/init:dev
  - wombat/runc:dev
  - wombat/containerd:dev
  - wombat/ca-certificates:dev
onboot:
  - name: sysctl
    image: wombat/sysctl:dev
    pid: "host"
    capabilities:
      - CAP_SYS_ADMIN
    binds:
      - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: wombat/sysfs:dev
    net: new
    ipc: new
  - name: dhcpcd
    image: wombat/dhcpcd:dev
    binds:
      - /run/resolvconf:/etc
    capabilities:
      - CAP_NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_SYS_ADMIN
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: wombat/metadata:dev
    binds:
      - /dev:/dev
      - /var:/var
      - /run:/run
      - /sys:/sys
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/ssl/certs:/etc/ssl/certs
    tmpfs:
      - /tmp
    readonly: true
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_NET_ADMIN
  - name: format
    image: wombat/format:dev
    binds:
      - /dev:/dev
    capabilities:
      - CAP_SYS_ADMIN
      - CAP_MKNOD
    net: new
    ipc: new
  - name: mounts
    image: wombat/mount:dev
    command: ["/usr/bin/mountie", "/var/lib/"]
    binds:
      - /dev:/dev
      - /var:/var:rshared,rbind
      - /:/hostroot
    capabilities:
      - CAP_SYS_ADMIN
    rootfsPropagation: shared
    net: new
    ipc: new
  - name: bridge
    image: busybox:latest
    runtime:
      mkdir: ["/var/lib/cni/conf","/var/lib/cni/bin"]
services:
  - name: getty
    image: wombat/getty:dev
    env:
     - INSECURE=true
    cgroupsPath: systemreserved/getty
    pid: host
    net: host
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /dev:/dev
      - /sys:/sys
    capabilities:
      - all
  - name: rngd
    image: wombat/rngd:dev
    cgroupsPath: systemreserved/rngd
    capabilities:
      - CAP_SYS_ADMIN
    oomScoreAdj: -800
    readonly: true
    net: new
    ipc: new
  - name: ntpd
    image: wombat/openntpd:dev
    cgroupsPath: systemreserved/ntpd
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
    capabilities:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
      - CAP_SYS_CHROOT
      - CAP_SETUID
      - CAP_SETGID
  - name: sshd
    image: wombat/sshd:dev
    cgroupsPath: systemreserved/sshd
    pid: host
    binds:
      - /root/.ssh:/root/.ssh
      - /etc/resolv.conf:/etc/resolv.conf
      - /run:/run
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /usr/bin/ctr:/usr/bin/ctr
      - /usr/bin/runc:/usr/bin/runc
      - /containers:/containers
      - /var/log:/var/log
      - /dev:/dev
      - /sys:/sys
    capabilities:
      - all
  - name: kubelet
    image: wombat/kubelet:dev
    cgroupsPath: podruntime/kubelet
    binds:
      - /tmp:/tmp
      - /dev:/dev
      - /usr/bin/ctr:/usr/bin/ctr
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/os-release:/etc/os-release
      - /etc/kubelet.sh.conf:/etc/kubelet.sh.conf
      - /run:/run:rshared,rbind
      - /var:/var:rshared,rbind
      - /var/lib/kubeadm:/etc/kubernetes
      - /etc/kubeadm:/etc/kubeadm
      - /var/lib/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins:rshared,rbind
      - /var/lib/cni/conf:/etc/cni/net.d:rshared,rbind
      - /var/lib/cni/bin:/opt/cni/bin:rshared,rbind
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock
    mounts:
      - type: bind
        source: /sys/fs/cgroup
        destination: /sys/fs/cgroup
        options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
    capabilities:
      - all
    rootfsPropagation: shared
    pid: host
    runtime:
      cgroups:
        - systemreserved
        - podruntime
        - kubepods
      mkdir:
        - /var/lib/kubeadm
        - /var/lib/cni/conf
        - /var/lib/cni/bin
        - /var/lib/kubelet-plugins
        - /var/lib/nfs/statd/sm
      mounts:
        - type: bind
          source: /var/lib/cni/bin
          destination: /opt/cni/bin
          options: ["rw","bind"]
        - type: bind
          source: /var/lib/cni/conf
          destination: /etc/cni/net.d
          options: ["rw","bind"]
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: etc/os-release
    contents: |
      PRETTY_NAME="Kubernit Project"
  - path: usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: etc/kubeadm/
    directory: true
  - path: etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: etc/cni/net.d
    directory: true
  - path: opt/cni/bin
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_babylon.pub
    mode: "0600"
    optional: true
  - path: etc/kubeadm/init
    contents: "--ignore-preflight-errors all"
  - path: etc/kubeadm/kube-system.init/00-init.yaml
    source: config/deploy/init.yaml
  - path: etc/kubeadm/kube-system.init/10-network.yaml
    source: config/deploy/net.yaml
  - path: etc/kubeadm/kube-system.init/20-helm.yaml
    source: config/deploy/helm.yaml
  - path: etc/kubeadm/kubeadm.yaml
    source: config/master/kubeadm.yaml
  - path: etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--node-ip=192.168.58.10"
