---
# Source: flux/templates/kube.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-kube-config
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: default
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []

---
# Source: flux/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
---
# Source: flux/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
  - name: flux
    namespace: "default"
    kind: ServiceAccount
---
# Source: flux/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flux
    release: RELEASE-NAME

---
# Source: flux/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: RELEASE-NAME
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux
        release: RELEASE-NAME
    spec:
      serviceAccountName: flux
      volumes:
      - name: kubedir
        configMap:
          name: flux-kube-config
      - name: git-key
        secret:
          secretName: flux-ssh
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
        - name: flux
          image: "quay.io/weaveworks/flux:1.10.1"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 3030
            protocol: TCP
          volumeMounts:
          - name: kubedir
            mountPath: /root/.kubectl
          - name: git-key
            mountPath: /etc/fluxd/ssh
            readOnly: true
          - name: git-keygen
            mountPath: /var/fluxd/keygen
          env:
          - name: KUBECONFIG
            value: /root/.kubectl/config
          args:
          - --ssh-keygen-dir=/var/fluxd/keygen
          - --k8s-secret-name=flux-ssh
          - --memcached-hostname=flux-memcached
          - --memcached-service=
          - --git-url=ssh://git@github.com/krubot/kubernit
          - --git-branch=master
          - --git-path=
          - --git-user=Weave Flux
          - --git-email=support@weave.works
          - --git-set-author=false
          - --git-poll-interval=5m
          - --git-timeout=20s
          - --sync-interval=5m
          - --git-ci-skip=false
          - --registry-poll-interval=5m
          - --registry-rps=200
          - --registry-burst=125
          - --registry-trace=false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi


---
# Source: flux/templates/memcached.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-memcached
  labels:
    app: flux-memcached
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flux-memcached
      release: RELEASE-NAME
  template:
    metadata:
      labels:
        app: flux-memcached
        release: RELEASE-NAME
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 128    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -I 5m #  Maximum size for one item
        ports:
        - name: memcached
          containerPort: 11211
        resources:
          {}

---
apiVersion: v1
kind: Service
metadata:
  name: flux-memcached
  labels:
    app: flux-memcached
    chart: flux-0.6.3
    release: RELEASE-NAME
    heritage: Tiller
spec:
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: flux-memcached
    release: RELEASE-NAME
