apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: tiller
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: tiller-cluster-rule
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: tiller
        namespace: kube-system
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: helm
        name: tiller
      name: tiller-deploy
      namespace: kube-system
    spec:
      ports:
        - name: tiller
          port: 44135
          protocol: TCP
          targetPort: tiller
      selector:
        app: helm
        name: tiller
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "2"
      labels:
        app: helm
        name: tiller
      name: tiller-deploy
      namespace: kube-system
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: helm
          name: tiller
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: helm
            name: tiller
        spec:
          containers:
            - env:
              - name: TILLER_NAMESPACE
                value: kube-system
              - name: TILLER_HISTORY_MAX
                value: "0"
              image: gcr.io/kubernetes-helm/tiller:canary
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /liveness
                  port: 44135
                  scheme: HTTP
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: tiller
              ports:
                - containerPort: 44134
                  name: tiller
                  protocol: TCP
                - containerPort: 44135
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /readiness
                  port: 44135
                  scheme: HTTP
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          serviceAccount: tiller
          tolerations:
            - effect: NoExecute
              key: node.kubernetes.io/not-ready
              operator: Exists
              tolerationSeconds: 300
            - effect: NoExecute
              key: node.kubernetes.io/unreachable
              operator: Exists
              tolerationSeconds: 300
