apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flux.fullname" . }}
  labels:
    app: {{ template "flux.name" . }}
    chart: {{ template "flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flux.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flux.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "flux.serviceAccountName" . }}
      {{- end }}
      volumes:
      - name: sshdir
        configMap:
          name: {{ template "flux.fullname" . }}-ssh-config
          defaultMode: 0600
      - name: git-key
        secret:
          secretName: {{ template "flux.fullname" . }}-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 3030
            protocol: TCP
          volumeMounts:
          - name: sshdir
            mountPath: /root/.ssh
            readOnly: true
          - name: git-key
            mountPath: /etc/fluxd/ssh
            readOnly: true
          - name: git-keygen
            mountPath: /var/fluxd/keygen
          args:
          - --ssh-keygen-dir=/var/fluxd/keygen
          - --k8s-secret-name={{ template "flux.fullname" . }}-git-deploy
          - --memcached-hostname={{ template "flux.fullname" . }}-memcached
          - --git-url={{ .Values.git.url }}
          - --git-branch={{ .Values.git.branch }}
          - --git-path={{ .Values.git.path }}
          - --git-user={{ .Values.git.user }}
          - --git-email={{ .Values.git.email }}
          - --git-poll-interval={{ .Values.git.pollInterval }}
          - --sync-interval={{ .Values.git.pollInterval }}
          {{- if .Values.token }}
          - --connect=wss://cloud.weave.works/api/flux
          - --token={{ .Values.token }}
          {{- end }}
          {{- if .Values.additionalArgs }}
          {{ toYaml .Values.additionalArgs }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
