apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flux.fullname" . }}-memcached
  labels:
    app: {{ template "flux.name" . }}-memcached
    chart: {{ template "flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "flux.name" . }}-memcached
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flux.name" . }}-memcached
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 64    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -vv    # This gets us to the level of request logs.
        ports:
        - name: memcached
          containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flux.fullname" . }}-memcached
  labels:
    app: {{ template "flux.name" . }}-memcached
    chart: {{ template "flux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app: {{ template "flux.name" . }}-memcached
    release: {{ .Release.Name }}
