
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-backup-operator
  labels:
    app: etcd-backup-operator

apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-operator
  labels:
    app: etcd-operator

apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-restore-operator
  labels:
    app: etcd-restore-operator

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-operator
  labels:
    app: etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: etcd-operator-etcd-backup-operator
  labels:
    app: etcd-operator
subjects:
- kind: ServiceAccount
  name: etcd-operator-etcd-backup-operator
  namespace: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator-etcd-operator

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-operator
  labels:
    app: etcd-operator
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-etcd-operator-etcd-operator
  namespace: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-etcd-operator-etcd-operator

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-restore-operator
  labels:
    chart: "etcd-operator-0.8.0"
    app: etcd-restore-operator
    heritage: Tiller
    release: RELEASE-NAME
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-etcd-operator-etcd-restore-operator
  namespace: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-etcd-operator-etcd-operator

apiVersion: v1
kind: Service
metadata:
  name: etcd-restore-operator
  labels:
    chart: "etcd-operator-0.8.0"
    app: etcd-restore-operator
    heritage: Tiller
    release: RELEASE-NAME
spec:
  ports:
  - protocol: TCP
    name: http-etcd-restore-port
    port: 19999
  selector:
    app: etcd-restore-operator
    release: RELEASE-NAME

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-backup-operator
  labels:
    chart: "etcd-operator-0.8.0"
    app: etcd-backup-operator
    heritage: Tiller
    release: RELEASE-NAME
spec:
  selector:
    matchLabels:
      app: RELEASE-NAME-etcd-operator-etcd-backup-operator
      release: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      name: RELEASE-NAME-etcd-operator-etcd-backup-operator
      labels:
        app: RELEASE-NAME-etcd-operator-etcd-backup-operator
        release: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-etcd-operator-etcd-backup-operator
      containers:
      - name: etcd-backup-operator
        image: "quay.io/coreos/etcd-operator:v0.9.2"
        imagePullPolicy: Always
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.8.0"
    app: etcd-operator
    heritage: Tiller
    release: RELEASE-NAME
spec:
  selector:
    matchLabels:
      app: RELEASE-NAME-etcd-operator-etcd-operator
      release: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      name: RELEASE-NAME-etcd-operator-etcd-operator
      labels:
        app: RELEASE-NAME-etcd-operator-etcd-operator
        release: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-etcd-operator-etcd-operator
      containers:
      - name: RELEASE-NAME-etcd-operator-etcd-operator
        image: "quay.io/coreos/etcd-operator:v0.9.2"
        imagePullPolicy: Always
        command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: RELEASE-NAME-etcd-operator-etcd-restore-operator
  labels:
    chart: "etcd-operator-0.8.0"
    app: etcd-restore-operator
    heritage: Tiller
    release: RELEASE-NAME
spec:
  selector:
    matchLabels:
      app: etcd-restore-operator
      release: RELEASE-NAME
  replicas: 1
  template:
    metadata:
      name: RELEASE-NAME-etcd-operator-etcd-restore-operator
      labels:
        app: etcd-restore-operator
        release: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-etcd-operator-etcd-restore-operator
      containers:
      - name: etcd-restore-operator
        image: "quay.io/coreos/etcd-operator:v0.9.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 19999
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: "etcd-restore-operator:19999"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
