---

apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  labels:
    chart: prometheus-operator
spec:
  chartGitPath: terraform-operator
