apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: ingress
      labels:
        name: ingress
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: cert-manager
      labels:
        name: cert-manager
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: monitoring
      labels:
        name: monitoring
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: dashboard
      labels:
        name: dashboard
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: alerting
      labels:
        name: alerting
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: private-network
      labels:
        name: private-network
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: identity-manager
      labels:
        name: identity-manager
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: logging
      labels:
        name: logging
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: intergration
      labels:
        name: intergration
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: analytics
      labels:
        name: analytics
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: testing
      labels:
        name: testing
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: project-tracking
      labels:
        name: project-tracking
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: storage
      labels:
        name: storage
