apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: ingress
      labels:
        name: ingress
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: certificates
      labels:
        name: certificates
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: monitoring
      labels:
        name: monitoring
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: storage
      labels:
        name: storage
